'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MapGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bush2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bush2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bush21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bush21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mouseicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mouseicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mouseicon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mouseicon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property signpost() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signpost", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceshipbottomleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceshipbottomleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceshipbottomright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceshipbottomright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceshiptopleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceshiptopleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceshiptopright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceshiptopright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treefruit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treefruit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treewood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treewood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathacross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathacross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathbottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathbottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathbottomleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathbottomleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathbottomright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathbottomright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathfull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathfull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathright1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathright1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtjunction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtjunction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtjunction4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtjunction4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtjunctionside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtjunctionside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtjunctionside2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtjunctionside2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtjunctionside3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtjunctionside3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtopleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtopleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodpathtopright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodpathtopright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property woodsskull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("woodsskull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
