'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MapTesting.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property al_behind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_behind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_behind1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_behind1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_behind2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_behind2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front_trial_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front_trial_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front_trial_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front_trial_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front_trial_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front_trial_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front_trial_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front_trial_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front_trial_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front_trial_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_front4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_front4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_left1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_left1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_left2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_left2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_right2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_right2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceship3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceship3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceship4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceship4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceshiplanding2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spaceshiplanding2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 120
        '''120
        '''120
        '''125
        '''120
        '''130
        '''120
        '''135
        '''125
        '''120
        '''125
        '''125
        '''125
        '''130
        '''125
        '''135
        '''130
        '''120
        '''130
        '''125
        '''130
        '''130
        '''130
        '''135
        '''135
        '''120
        '''135
        '''125
        '''135
        '''130
        '''135
        '''135
        '''140
        '''120
        '''140
        '''125
        '''140
        '''130
        '''140
        '''135
        '''145
        '''120
        '''145
        '''125
        '''145
        '''130
        '''145
        '''135
        '''150
        '''120
        '''150
        '''125
        '''150
        '''130
        '''150
        '''135
        '''155
        '''120
        '''155
        '''125
        '''155
        '''130
        '''155
        '''135
        '''120
        '''140
        '''120
        '''145
        '''120
        '''150
        '''120
        '''155
        '''125
        '''140
        '''125
        '''145
        '''125
        '''150
        '''125
        '''155
        '''130
        '''140
        '''130
        '''145
        '''130
        '''150
        '''130
        '''155
        '''135
        '''140
        '''135
        '''145
        '''135
        '''150
        '''135
        '''155
        '''140
        '''140
        '''140
        '''145
        '''140
        '''150
        '''14 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property spaceshiplanding2text() As String
            Get
                Return ResourceManager.GetString("spaceshiplanding2text", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
